version: '3.8'

services:
  jekyll:
    container_name: filmnetzwerk_homepage
    image: jekyll/builder:4
    volumes:
      - ./:/srv/jekyll:Z
    working_dir: /srv/jekyll
    command: jekyll serve --host 0.0.0.0
    ports:
      - "8081:4000"
